### ISSUE TITLE
На invite-лендинге описания удаленных продуктов

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#11]
http://p.icoach.io/invite/e25667d0

![2015-07-11 23 33 08](https://cloud.githubusercontent.com/assets/9354450/8635501/397c0ebc-2825-11e5-841f-eea95ae220fb.png)

Как изменить страницу лендинга и удалить продукты, которых уже нет в партнерке?

**Comment by schaman** [comment]
Продукты берутся из Aim. Удали Aim, они исчезнут с этой страницы.

У нас никак не проработано устаревание предложений. Я могу сделать галочку «Активен» у Aim, которая будет прятать Aim из партнёрского кабинета и с этой страницы. Поставить её можно будет в админе. Тогда устаревшие продукты мы сможем делать неактивными.

Но это нужно будет тогда, когда по устаревшим продуктам будут партнёрские продажи. Пока что проще удалить.
