### ISSUE TITLE
Не могу удалить price

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#13]
В [этом aim'е](http://p.icoach.io/admin/aim/3) два прайса удалил, один не могу. 

Выскакивает ошибка 500 при удалении прайса. 

Удаляю прайсы, чтобы весь этот aim удалить.

![2015-08-06 13 25 22](https://cloud.githubusercontent.com/assets/9354450/9110552/e34ddd80-3c3e-11e5-917c-090556ada7a0.png)

**Comment by schaman** [comment]
Зачем удалять price, и весь aim, по которым были продажи?

**Comment by kirilldudinsky** [comment]
Потому что мы этот тренинг больше не продаём

**Comment by kirilldudinsky** [comment]
Правильное решение: введение атрибута "снято с продажи" (добавить галочку), отображать серым в админском списке и скрывать продукт от партнёров
