### ISSUE TITLE
Теряется партнёрская ссылка

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#14]
Скачиваю [продукт 17 шагов](http://soedinennost.com/products/17-steps/) ([Aim здесь](http://p.icoach.io/admin/aim/48)) по своей партнерской ссылке с источником трафика: http://soedinennost.com/products/17-steps/?p=e25667d0&src=test7

Для этого захожу в защищенный режим Хрома

![image](https://cloud.githubusercontent.com/assets/9354450/9995757/0ba9bef2-6084-11e5-9d7d-16bf98818325.png)

Ввожу данные

![image](https://cloud.githubusercontent.com/assets/9354450/9995799/38f71576-6084-11e5-93da-04fd94b6bb5d.png)

Захожу в почту и подтверждаю емейл

![image](https://cloud.githubusercontent.com/assets/9354450/9995839/68eceef4-6084-11e5-9c37-cae71579b978.png)

Щетчики увеличились

В партнёрке:
![image](https://cloud.githubusercontent.com/assets/9354450/9995866/8e7d7e86-6084-11e5-8578-a0882bfa9c16.png)

В админке:
![image](https://cloud.githubusercontent.com/assets/9354450/9995883/ae70fb46-6084-11e5-8ce6-1f7ee685077c.png)

Теперь в письме "Добро пожаловать" нажимаю скачать недорогой платный продукт ([ссылка на оффер](http://prorealnost.com/offer/17-shagov-za-4-dnya)):
![image](https://cloud.githubusercontent.com/assets/9354450/9995901/ca0c5918-6084-11e5-84d5-776efaae713a.png)

и на самом лендинге нажимаю "заказать" и ввожу свои данные, перехожу на страницу с оплатой. 

Как видно [здесь](http://ic.icoach.io/admin/customer/23475) партнёрская ссылка потерялась с счетчик оплаты соответственно не увеличился.

![image](https://cloud.githubusercontent.com/assets/9354450/9996046/8155f818-6085-11e5-93a9-56d25aac112b.png)

Почему теряется партнёрская ссылка и как это исправить?

**Comment by schaman** [comment]
была прореальность-прореальность, а стала просто прореальность
