### ISSUE TITLE
Хочу посмотреть статистику по источникам траффика как партнер

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#4]
Вот [тут](http://p.icoach.io/admin/aim/1) отображается статистика

![2015-01-16 15 40 58](https://cloud.githubusercontent.com/assets/9354450/5777889/c4d67b9c-9d96-11e4-87d0-2414d47b8f24.png)

Дима зарегистрировался как партнер и хочет видеть и отслеживать эту статистику

Как ему это сделать?

**Comment by schaman** [comment]
Про источники трафика для партнёров написано тут: [http://p.icoach.io/partner/page/homepage](http://p.icoach.io/partner/page/homepage) в разделе «Источники трафика».

Для тебя руководство написано тут: [http://learn.icoach.io/doc/27](http://learn.icoach.io/doc/27)

Прошу тебя создать в Aim счётчики для всех продуктов, и указать партнёрские ссылки.
