### ISSUE TITLE
И все равно не работает метрика в партнерском кабинете

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#6]
Я создал новый [оффер](http://money.prorealnost.com/admin/offer/28) со старыми шотами.

Добавил ссылку на него в существующий [aim](http://p.icoach.io/admin/aim/1)

Задвоенные counter'ы в другой эйме удалил.

В Опере почиститл куки и зарегистрировался по ссылке из партнерки + src

http://money.prorealnost.com/offer/kak-zarabotat-60000-r-za-mesyac?p=e25667d0&src=testkirill3

В результате в [aim'е админа](http://p.icoach.io/admin/aim/1) вот такая картина

![2015-01-17 12 32 04](https://cloud.githubusercontent.com/assets/9354450/5788681/1ab02f5a-9e45-11e4-85f9-7c4ee5d12539.png)

А в [aim'е партнера](http://p.icoach.io/partner/aim/1)

вот что

![2015-01-17 12 32 27](https://cloud.githubusercontent.com/assets/9354450/5788684/32fe2508-9e45-11e4-94bc-da01b7e146e3.png)

**Comment by schaman** [comment]
fixed
