### ISSUE TITLE
Ошибка при заполнении поля payoff

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#8]
В [этом айме](http://p.icoach.io/admin/aim/20) хочу сделать payoff 100% от выручки. Т.е. retail 24€ \* 0,77 налоги = 18,48. Округляю до 18 Евро. Вставляю сумму 18 Евро в поле payoff и получаю ошибку 500

![2015-03-11 1 06 40](https://cloud.githubusercontent.com/assets/9354450/6587955/5ffe2372-c78b-11e4-96c9-d25aea593755.png)
![2015-03-11 1 06 48](https://cloud.githubusercontent.com/assets/9354450/6587956/600012f4-c78b-11e4-8b91-0f4cf870205c.png)
![2015-03-11 1 06 53](https://cloud.githubusercontent.com/assets/9354450/6587957/600247fe-c78b-11e4-97b7-13c060e9513a.png)
![2015-03-11 1 06 56](https://cloud.githubusercontent.com/assets/9354450/6587958/6005611e-c78b-11e4-8889-21325c70aceb.png)

**Comment by schaman** [comment]
Проблема в том, что CV <= 0.

Вывел формулы в редактор http://p.icoach.io/admin/aim/price/edit/20

Ошибка 500 исправлена: теперь если CV <= 0, то форму не сохранить, и в таблице отрицательные значения выделяются красным.

CV не может быть <= 0, потому что если меньше, то это убыток, а если 0, то партнёры второго уровня ничего не зарабатывают, а мы им обещали деньги с каждой сделки.
