### ISSUE TITLE
Хочу проверить, от какого партнера пришел контакт

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/p#9]
У меня есть [контакт](http://ic.icoach.io/admin/q/customer/22954), который заказал бесплатный продукт по бизнесу 11 секретов [ссылка на эйм](http://p.icoach.io/admin/aim/15).

От партнера Вера Суворова заказало этот бесплатный продукт 46 человек.

![2015-03-11 1 42 51](https://cloud.githubusercontent.com/assets/9354450/6588310/08bccf64-c790-11e4-9c6c-f972141884e9.png)

Кроме этого из каких-то неведомых двух мест заказало этот продукт еще 2+4 человека. Мы нигде этот продукт не пиарили. 

После этого мы сделали рассылку по людям, заказавшим этот 15 эйм и по людям, записанным на два бесплатных вебинара по бизнесу [список в mx](http://mx.icoach.io/admin/list/9).

В результате этого, курс оплатили два человека. [Артем](http://ic.icoach.io/admin/q/customer/22883) - у которого в истории написано, что он заказывал 11 секретов и все - и [Евгений](http://ic.icoach.io/admin/q/customer/22954) - у которого в истории вообще ничего не написано. 

**Хочу выяснить, пришли ли Артем и Евгений от партнера Вера Суворова.**

В mx'е написано, что нет. Но это очень странно, потому что мы нигде не пиарили 11 секретов, кроме как по рассылке Веры Суворовой, а значит Артем с высокой долей вероятности пришел от неё. А в случае с Евгением - я вообще не понимаю, как такое может быть, что он заказывает продукт, но у него в истории это первый заказ.

Мне нужен простой механизм для выяснения таких вопросов. 

Спасибо!

**Comment by schaman** [comment]
![2015-03-11 22-09-54 icoach](https://cloud.githubusercontent.com/assets/1928852/6604732/a737c990-c83b-11e4-80c5-570589825eb4.png)
